- docs/source/conf.py
- locopy/__init__.py
- locopy/_version.py
- locopy/errors.py
- locopy/locopy.py
- locopy/logger.py
- locopy/s3.py
- locopy/utility.py
- setup.py
- Adding long description
- Fixing headers
@theianrobertson if you don't mind taking a peek
> Setup pypi fix

- docs/source/examples.rst
missed a minor tweak in the docs.
> minor method call cleanup

- setup.py
Realized that pandas is missing from `setup.py`
> adding pandas to setup.py

- locopy/database.py
- tests/test_database.py
Minor enhancement to have a helper util to output rows as dictionaries.
@theianrobertson mind taking a look?
> adding to_dict functionality for outputting cursor results

- requirements-dev.txt
- tests/test_s3.py
- tests/test_snowflake.py
In this PR I am adding hypothesis tests. So far I mainly just changed a couple of the existing tests to use random payloads generated by hypothesis instead of using a single hardcoded value.
There are probably a few more easy hypothesis applications in our current test suite, but this is at least a start.
> Hypothesis testing

- locopy/_version.py
> bump version 0.3.2

- locopy/_version.py
Fixes #60 
- An small bug within the new `insert_dataframe_to_table` method
- Releasing a `0.3.3` on PyPi
> bump version 0.3.3

- locopy/database.py
- locopy/redshift.py
- locopy/snowflake.py
- tests/test_database.py
- tests/test_redshift.py
- tests/test_snowflake.py
This PR is promoting both `_connect` and `_disconnect` to public methods. I changed the tests accordingly.
> changed connect and disconnect from private to public

- requirements-dev.txt
- requirements.txt
- setup.py
In this PR I have changed the `==` for boto3 to `>=` in order to be less restrictive with the versions. This will close #73.
> bumped boto3 from == to >=

- locopy/utility.py
Minor fix to some extra print statements we have missed. Removed the data one and changes the column one to a debug logging.
> fix print statement

- .github/workflows/python-package.yml
- .pre-commit-config.yaml
- README.rst
- docs/source/developer.rst
- setup.cfg
- setup.py
- CLA verbiage was outdated
- Adding in `isort` to pre-commit
- cleaning up `setup.py`
> CLA and setup cleanup

- README.rst
- ROADMAP.rst
@elzzhu Adding some details on the project roadmap for the OSPO requirements.
> adding ROADMAP details

- .github/workflows/edgetest.yml
Adding edgetest action on a cron schedule
> adding edgetest action

- locopy/_version.py
bump version to 0.4.1 for new minor release
> bump version to 0.4.1

- setup.py
> Adding build to dev extras

- .github/workflows/edgetest.yml
- .github/workflows/publish-package.yml
- CODEOWNERS
- locopy/_version.py
- locopy/redshift.py
- locopy/snowflake.py
- locopy/utility.py
- pyproject.toml
- tests/test_utility.py
Release v0.5.4
===========
Fix:
- #226
House keeping
- #220
- #223 
- #224
- #227 
- #228 
- #230
> Release v0.5.4

- locopy/_version.py
Bump version to cut release with updated dependency versions
> Bump version

- locopy/_version.py
Version bump for a minor release
> version bump 0.5.6

- locopy/_version.py
cut a minor release with edgetest bumps.
> minor bump version

- locopy/_version.py
- pyproject.toml
Release v0.5.7
--------------
edgetest updates:
- #248 
- #249 
- #250 
- #251 
- #252 
- #253 
- and version bump (#254)
> Release v0.5.7

- locopy/_version.py
- pyproject.toml
Release v0.5.8
===========
Updating dependencies via `edgetest`
Dependency updates:
- #256 
- #257
- #258
- #259
- #260
- #261
- #262
Bump version:
- #263
> Release v0.5.8

- locopy/_version.py
- requirements.txt
Fix for Issue #274, and PR #275
> urllib3 vulnerability

- .github/workflows/edgetest.yml
Updating run-edgetest-actionto v1.6 for upcoming release: https://github.com/edgetest-dev/run-edgetest-action/pull/23
> Update edgetest.yml to run-edgetest-action@v1.6

- locopy/_version.py
> bump version to 0.6.4
