- locopy/locopy.py
- locopy/s3.py
- tests/test_integration.py
- tests/test_locopy.py
- tests/test_s3.py
@theianrobertson wondering if you can take a look. 
Funnily enough @ian-whitestone had requested this feature a while back. He wanted to just use the S3 functionality to move data to S3 and back, and **not always** have to provide redshift credentials. This should solve for this by having a extra flag which people can turn on when using `S3` and it will bypass the `Cmd.__init__` 
Open to alternative ways, but this seems fairly simple for now.
> S3 without rs creds

- requirements-dev.txt
- requirements.txt
- setup.py
@theianrobertson do you mind reviewing this?
- Essentially there is a venerability with `pyyaml`. See: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342
- going from `3.12` to `4.2b4` provides a fix. 
- we are only using `pyyaml` for reading in configs so there shouldn't be any particular regressions
- unit and integration tests are working good
- will pin to a more stable version down the road once `4.2` is officially released.
> updating pyyaml to fix #25

- locopy/s3.py
- locopy/snowflake.py
- tests/test_snowflake.py
- Fixes #36 
- Seems like a few warnings in the tests popped up with regards to `\s`. Making them raw suppresses the warnings from `pytest` runs
> Sphinx default fix

- docs/source/snowflake.rst
- locopy/snowflake.py
- tests/data/mock_file.json
- tests/test_integration_sf.py
- tests/test_snowflake.py
@theianrobertson If you have a chance to take a peek
This should close #38 
- small tweaks to `GET` and `PUT` to use `PurePath`.
- removing hardened use of `csv` only. Now supports `csv`, `json`, and `parquet`
- one note is there is no explicit validation of `format_options` which is still just a list of strings as before. (ex: `["FIELD_DELIMITER=','", "TRIM_SPACE = TRUE"]`)
- The `copy` and `unload` methods have a slightly different signatures as we aren't always assuming csv formatting
> Additonal sf file type support

- .gitignore
- locopy/database.py
- locopy/logger.py
- locopy/redshift.py
- locopy/s3.py
- locopy/snowflake.py
- locopy/utility.py
- requirements-dev.txt
- requirements.txt
- setup.py
Closes #41 
- Switching from the standard logging to `loguru`, and associated changes to the actual messages to follow `{}` formatting.
- small tweak to `setup.py` so that it will read `requirements.txt`
@theianrobertson Appreciate your thoughts
> switch logging to Loguru

- locopy/_version.py
- requirements.txt
Should close #43, this just bumps to a later version of PyYaml and changes from a strict version to a minimum version.
> Move to latest version of pyyaml and bump patch version

- locopy/database.py
- locopy/snowflake.py
- requirements-dev.txt
- tests/conftest.py
- tests/test_database.py
- tests/test_redshift.py
- tests/test_snowflake.py
In this pull request I have added support for SQLite as well as an additional feature for Snowflake users. If the user supplies `schema` in their credentials, `locopy.snowflake.Snowflake` will run `USE SCHEMA {schema}` for the user.
Fixes #50 
Fixes #55
> Adding support for SQLite

- locopy/_version.py
Cutting new release of `locopy` (0.3.4):
- Contains a small bug fix for the snowflake dataframe dtype checking (#64)
- Switched the private connect and disconnect to public. (#63). Allows for more intuitive usages outside the `with` context.
> bump version 0.3.4

- locopy/_version.py
Cutting new release of locopy (0.3.5):
- Contains a small bug fix for #66
> bump version 0.3.5

- locopy/_version.py
Cutting new release of `locopy` (0.3.6):
- logging typo fix (#70)
- switching back to standard logging (#72) 
- relaxing requirements file ( #74)
> bump version 0.3.6

- locopy/database.py
- locopy/redshift.py
- locopy/utility.py
- tests/test_integration.py
- tests/test_redshift.py
Several changes in this commit
1. added boolean type to `find_column_type()` in `utility.py`
2. used pd.to_datetime and pd.to_numeric to stop doing row wise calculation. see details in issue #67 
3. added `insert_dataframe_to_table` to redshift class. 
4. added all relevant testing.
> Add function to insert pandas dataframe to redshift

- .pre-commit-config.yaml
- docs/source/developer.rst
- docs/source/index.rst
- Updating developer docs to outline release process and purposes of each of the branches.
- I've also added the `develop` and moving forward this will be the default branch.
- Did a bit of clean up in the docs and added an API section to align to `datacompy`
Closes #79
> Developer doc updates

- locopy/snowflake.py
- tests/test_snowflake.py
Fixes #84 
- Fairly simple enhancement to expose the `OVERWRITE` option in the Snowflake `PUT` command when uploading to the internal stage.
> Put overwrite

- locopy/database.py
- locopy/errors.py
- locopy/redshift.py
- locopy/s3.py
- locopy/snowflake.py
- locopy/utility.py
- tests/data/mock_file_header.txt
- tests/test_integration.py
- tests/test_redshift.py
- tests/test_utility.py
PR to help fix the issue #87 
The intent here is to:
- Look for `IGNOREHEADER` and extract out the number of rows.
- if `IGNOREHEADER` exists and splits > 1 then we remove the headers form the file when we split and remove it from the options and load into RS.
Would like some eyes on this this there is a bit going on. I tried to make some util functions to help break down things a little bit.
> Ignoreheader fix

- locopy/utility.py
This should fix the YAML issue and not cause any adverse affects. Since we are only using the pyyaml for reading in some small db configs the safe load should be more than enough and not interfere with anything else.
Closes #100
> switching to safe_load. Fixes #100

- README.rst
- docs/source/index.rst
- setup.py
The name change caused some broken links. This should fix them.
> fixing repo name change to locopy

- locopy/redshift.py
- tests/test_redshift.py
Adding a small bug fix. Seems like we were missing importing an exception. Including a simple test too.
> Import bug fix

- .github/workflows/edgetest.yml
- Fixes #222 
- bumps up the action version which should support `pyproject.toml` now.
> Update edgetest action to 1.3

- locopy/redshift.py
- locopy/snowflake.py
- locopy/utility.py
- tests/test_utility.py
- Updated find_column_type method to only map columns types to date if they contain data with valid Snowflake date formats
- Added warehouse parameter to find_column_type method to differentiate column type mappings based on warehouse type (only affects dates)
- Updated test and internal calls of find_column_type
Fixes #221
> find_column_type fix for snowflake dates

- locopy/utility.py
- tests/test_utility.py
Fixes #271 
Extend `find_column_type` to parse addition pandas dtype.
Added test to verify this functionality
> add support for parsing newer pandas dtype

- locopy/database.py
- tests/test_database.py
- Reduce mocking in test suite and compared dataframes directly. 
- Fixed a bug where `pandas.DataFrame` could be called with non empty data but `columns=[]` which will error out in pandas backend.
> Reduced mocking in test suite, fixed minor bug

- locopy/utility.py
- pyproject.toml
- tests/test_utility.py
- first, check if datatype is a `pd.ArrowDtype`, if it is, call `check_column_type_pyarrow` to parse pyarrow-backed datatypes 
- else, parse as before
Fixes #282
> add pyarrow support in find_column_type for pandas dataframes

- tests/test_utility.py
Fix datatype for test data to account for calling pyarrow specific datatype as string support which is only available in pandas 2.0 onwards, but package supports pandas 1.5.0
> fix test to be compatible with pandas 1.5.0
